framework:
    messenger:
        failure_transport: failed

        transports:
            # Envoie immédiat des messages sans passer par une queue asynchrone
            async: 'sync://'

            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route tes messages ici si nécessaire
            # 'App\Message\YourMessage': async
